apiVersion: v1
kind: Service
metadata:
  name: offer-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: offer-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: offer-postgres
spec:
  serviceName: "offer-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: offer-postgres
  template:
    metadata:
      labels:
        app: offer-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: offer_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
