apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  database_url: postgresql+asyncpg://myuser:mypassword@offer-postgres:5432/offer_db  #//5wAG8AcwB0AGcAcgBlAHMAcQBsACsAYQBzAHkAbgBjAHAAZwA6AC8ALwBtAHkAdQBzAGUAcgA6AG0AeQBwAGEAcwBzAHcAbwByAGQAQABvAGYAZgBlAHIALQBwAG8AcwB0AGcAcgBlAHMAOgA1ADQAMwAyAC8AbwBmAGYAZQByAF8AZABiAA0ACgA=
  
  # postgresql+asyncpg://myuser:mypassword@offer-postgres:5432/offer_db
