apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  database_url: postgresql+asyncpg://myuser:mypassword@offer-postgres:5432/offer_db  #//5wAG8AcwB0AGcAcgBlAHMAcQBsACsAYQBzAHkAbgBjAHAAZwA6AC8ALwBtAHkAdQBzAGUAcgA6AG0AeQBwAGEAcwBzAHcAbwByAGQAQABvAGYAZgBlAHIALQBwAG8AcwB0AGcAcgBlAHMAOgA1ADQAMwAyAC8AbwBmAGYAZQByAF8AZABiAA0ACgA=
  auth_secret_key: uLz#y49&m9@P3Ks^WdX!2*GnV7b$XrAq
  
  # postgresql+asyncpg://myuser:mypassword@offer-postgres:5432/offer_db
